Adding Llama2 fine tuning on Slurm
GoogleCloudPlatform/scientific-computing-examples pull request #74
Opened 2024-04-15 19:02 UTC by jrossthomson

Looking to get the Llama 2 fine tuning published. Based on work by Injae Kwak.

Cleaned up the conda install. Detailed instructions.  HPC Toolkit page also to be published.

2024-04-25 18:25 UTC, wkharold requested changes
I was not able to get any L4s, I do have the quota, but everything else seemed to work as expected. I like using the `gcloud` commands, it's up to you.

2024-04-25 18:25 UTC, wkharold commented on llama2-finetuning-slurm/README.md
> +gsutil -m cp -r gs://vertex-model-garden-public-us-central1/llama2/llama2-7b-hf/ .
Alternative `gcloud` download command
```bash
gcloud storage cp --recursive gs://vertex-model-garden-public-us-central1/llama2/llama2-7b-hf/ .
```

2024-04-25 18:25 UTC, wkharold commented on llama2-finetuning-slurm/README.md
> +
Go direct to the login node via
```bash
gcloud compute ssh $(gcloud compute instances list --filter "name ~ login" --format "value(name)") --tunnel-through-iap --zone us-east1-b
```

2024-04-26 14:01 UTC, jrossthomson commented on llama2-finetuning-slurm/README.md
> +    cd ai-infrastructure
Done

2024-04-26 14:49 UTC, wkharold approved these changes
LGTM

2024-04-26 14:50 UTC, merged